/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application_trafic;

import Modele.MouvementTableModel;
import RequeteReponseTRAMAP.ReponseTRAMAP;
import RequeteReponseTRAMAP.RequeteTRAMAP;
import Utils.Convert;
import Utils.DataSet;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julien
 */
public class ListOperationsForm extends javax.swing.JDialog
{
    private Socket CSocket;
    
    /**
     * Creates new form LostOperationsForm
     */
    public ListOperationsForm(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }
    
    public ListOperationsForm(java.awt.Frame parent, boolean modal, Socket CSocket)
    {
        super(parent, modal);
        initComponents();
        this.CSocket = CSocket;
        tblMouvements.setModel(new MouvementTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        lblDateArrivee = new javax.swing.JLabel();
        lblDateDepart = new javax.swing.JLabel();
        tfdDateArrivee1 = new javax.swing.JTextField();
        tfdDateArrivee2 = new javax.swing.JTextField();
        lblNomSociete = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMouvements = new javax.swing.JTable();
        btnBySociete = new javax.swing.JButton();
        btnByDestination = new javax.swing.JButton();
        cbxSociete = new javax.swing.JComboBox();
        cbxDestination = new javax.swing.JComboBox();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDateArrivee.setText("Date arrivée 1 : ");

        lblDateDepart.setText("Date arrivée 2 : ");

        tfdDateArrivee1.setText("JJ/MM/AAAA");

        tfdDateArrivee2.setText("JJ/MM/AAAA");

        lblNomSociete.setText("Nom de la société : ");

        lblDestination.setText("Destination : ");

        tblMouvements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMouvements);

        btnBySociete.setText("Afficher les mouvements pour une société");
        btnBySociete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBySocieteActionPerformed(evt);
            }
        });

        btnByDestination.setText("Afficher les mouvements pour une destination");
        btnByDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnByDestinationActionPerformed(evt);
            }
        });

        cbxSociete.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1207, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateArrivee)
                            .addComponent(lblDateDepart))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfdDateArrivee2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDestination)
                                .addGap(34, 34, 34)
                                .addComponent(cbxDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfdDateArrivee1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomSociete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxSociete, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(btnBySociete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnByDestination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDateArrivee)
                    .addComponent(tfdDateArrivee1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomSociete)
                    .addComponent(cbxSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDateDepart)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdDateArrivee2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDestination)
                        .addComponent(cbxDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnByDestination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBySociete)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBySocieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBySocieteActionPerformed
        if(!tfdDateArrivee1.getText().isEmpty() && !tfdDateArrivee2.getText().isEmpty())
        {
            String strListRequest = "SOCIETE#" + (String)cbxSociete.getSelectedItem() + "#" + tfdDateArrivee1.getText() + "#" + tfdDateArrivee2.getText();
            try
            {
                RequeteTRAMAP req = new RequeteTRAMAP(RequeteTRAMAP.REQUEST_LIST_OPERATIONS, strListRequest);
                ObjectOutputStream oos = null;
                oos = new ObjectOutputStream(CSocket.getOutputStream());
                oos.writeObject(req);
                oos.flush();

                ObjectInputStream ois = null;
                ois = new ObjectInputStream(CSocket.getInputStream());
                ReponseTRAMAP rep = (ReponseTRAMAP)ois.readObject();

                if(rep.getCode() == ReponseTRAMAP.REPONSE_OK)
                {
                    DataSet ds = (DataSet)rep.getResult();
                    Convert.DisplayResult(tblMouvements, ds);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, (String)rep.getResult(), "Echec de la connexion", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (IOException ex)
            {
                Logger.getLogger(ListOperationsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (ClassNotFoundException ex) 
            {
                Logger.getLogger(ListOperationsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Les dates sont obligatoires.", "Titre", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnBySocieteActionPerformed

    private void btnByDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnByDestinationActionPerformed
        if(!tfdDateArrivee1.getText().isEmpty() && !tfdDateArrivee2.getText().isEmpty())
        {
            String strListRequest = "DESTINATION#" + (String)cbxDestination.getSelectedItem() + "#" + tfdDateArrivee1.getText() + "#" + tfdDateArrivee2.getText() + "#";
            try
            {
                RequeteTRAMAP req = new RequeteTRAMAP(RequeteTRAMAP.REQUEST_LIST_OPERATIONS, strListRequest);
                ObjectOutputStream oos = null;
                oos = new ObjectOutputStream(CSocket.getOutputStream());
                oos.writeObject(req);
                oos.flush();

                ObjectInputStream ois = null;
                ois = new ObjectInputStream(CSocket.getInputStream());
                ReponseTRAMAP rep = (ReponseTRAMAP)ois.readObject();

                if(rep.getCode() == ReponseTRAMAP.REPONSE_OK)
                {
                    DataSet ds = (DataSet)rep.getResult();
                    Convert.DisplayResult(tblMouvements, ds);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, (String)rep.getResult(), "Echec de la connexion", JOptionPane.ERROR_MESSAGE);
                }
            }
            catch (IOException ex)
            {
                Logger.getLogger(ListOperationsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            catch (ClassNotFoundException ex) 
            {
                Logger.getLogger(ListOperationsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Les dates sont obligatoires.", "Titre", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnByDestinationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOperationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOperationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOperationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOperationsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListOperationsForm dialog = new ListOperationsForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnByDestination;
    private javax.swing.JButton btnBySociete;
    private javax.swing.JComboBox cbxDestination;
    private javax.swing.JComboBox cbxSociete;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDateArrivee;
    private javax.swing.JLabel lblDateDepart;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblNomSociete;
    private javax.swing.JTable tblMouvements;
    private javax.swing.JTextField tfdDateArrivee1;
    private javax.swing.JTextField tfdDateArrivee2;
    // End of variables declaration//GEN-END:variables

    void setModelComboBoxDestination(DefaultComboBoxModel dcbm)
    {
        cbxDestination.setModel(dcbm);
    }

    void setModelComboBoxSociete(DefaultComboBoxModel dcbm)
    {
        cbxSociete.setModel(dcbm);
    }
}
