/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package applictestbeanbd;

import AccessBD.BeanBDAccess;
import Queries.QuerySelect;
import Queries.QueryUpdate;
import java.sql.Array;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Julien
 */
public class UpdateForm extends javax.swing.JDialog
{
    private QueryUpdate Query;
    private BeanBDAccess Bean;
    private ResultSet RS;
    /**
     * Creates new form UpdateForm
     */
    public UpdateForm(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }
    
    public UpdateForm(java.awt.Frame parent, boolean modal, BeanBDAccess Bean, String TableCible)
    {
        super(parent, modal);
        initComponents();
        this.Bean = Bean;
        tfdTableCible.setText(TableCible);
        initComboBox();
        Query = new QueryUpdate(TableCible);
    }
    
    private void initComboBox()
    {
        try
        {
            RS = Bean.Select(new QuerySelect("*", tfdTableCible.getText()));
            DefaultComboBoxModel DCBM = new DefaultComboBoxModel();
            while(RS.next())
                DCBM.addElement(RS.getString("Ville"));
            cbxVille.setModel(DCBM);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(UpdateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTableCible = new javax.swing.JLabel();
        tfdTableCible = new javax.swing.JTextField();
        cbxVille = new javax.swing.JComboBox();
        lblVille = new javax.swing.JLabel();
        lblDistanceBateau = new javax.swing.JLabel();
        lblDistanceTrain = new javax.swing.JLabel();
        lblDistanceRoute = new javax.swing.JLabel();
        tfdDistanceBateau = new javax.swing.JTextField();
        tfdDistanceTrain = new javax.swing.JTextField();
        tfdDistanceRoute = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTableCible.setText("Table cible :");

        tfdTableCible.setEditable(false);

        cbxVille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxVille.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxVilleItemStateChanged(evt);
            }
        });

        lblVille.setText("Ville : ");

        lblDistanceBateau.setText("Distance par bateau : ");

        lblDistanceTrain.setText("Distance par train : ");

        lblDistanceRoute.setText("Distance par route : ");

        btnValider.setText("Valider les changements de valeurs");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValider, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTableCible)
                            .addComponent(lblVille))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxVille, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfdTableCible)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDistanceBateau)
                            .addComponent(lblDistanceTrain)
                            .addComponent(lblDistanceRoute))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfdDistanceBateau)
                            .addComponent(tfdDistanceTrain)
                            .addComponent(tfdDistanceRoute))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTableCible)
                    .addComponent(tfdTableCible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVille))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistanceBateau)
                    .addComponent(tfdDistanceBateau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistanceTrain)
                    .addComponent(tfdDistanceTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistanceRoute)
                    .addComponent(tfdDistanceRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnValider)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        try 
        {
            LinkedList<String> list = new LinkedList<>();
            list.add(tfdDistanceBateau.getText());
            list.add(tfdDistanceTrain.getText());
            if(tfdDistanceRoute.getText().isEmpty())
                list.add(null);
            else
                list.add(tfdDistanceRoute.getText());
            ResultSetMetaData RSMD = RS.getMetaData();
            int nbreColonne = RSMD.getColumnCount();
            for(int i = 1, j = 0; i <= nbreColonne; i++)
            {
                if(i == 1)
                    getQuery().AddWhere(RSMD.getColumnName(i) + " = '" + RS.getString("Ville") + "'");
                else
                {
                    getQuery().AddValue(RSMD.getColumnName(i), list.get(j));
                    j++;
                }
            }
            this.dispose();
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(UpdateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnValiderActionPerformed

    private void cbxVilleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxVilleItemStateChanged
        try
        {
            RS.beforeFirst();
            while(RS.next())
            {
                if(RS.getString("Ville").equals(cbxVille.getSelectedItem()))
                {
                    tfdDistanceBateau.setText(RS.getString("DistanceBateau"));
                    tfdDistanceTrain.setText(RS.getString("DistanceTrain"));
                    tfdDistanceRoute.setText(RS.getString("DistanceRoute"));
                    break;
                }
            }
        } 
        catch (SQLException ex)
        {
            Logger.getLogger(UpdateForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxVilleItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateForm dialog = new UpdateForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValider;
    private javax.swing.JComboBox cbxVille;
    private javax.swing.JLabel lblDistanceBateau;
    private javax.swing.JLabel lblDistanceRoute;
    private javax.swing.JLabel lblDistanceTrain;
    private javax.swing.JLabel lblTableCible;
    private javax.swing.JLabel lblVille;
    private javax.swing.JTextField tfdDistanceBateau;
    private javax.swing.JTextField tfdDistanceRoute;
    private javax.swing.JTextField tfdDistanceTrain;
    private javax.swing.JTextField tfdTableCible;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Query
     */
    public QueryUpdate getQuery() {
        return Query;
    }

    /**
     * @param Query the Query to set
     */
    public void setQuery(QueryUpdate Query) {
        this.Query = Query;
    }
}
